course = " Python programming "
print(course.upper())
print(course.lower())
print(course.title())
print(course.strip())
print(course.rstrip())
print(course.find("pro"))
print(course.replace("P", "J"))
print("pro" in course)
print("abc" not in course)
