import pandas as pd
df = pd.DataFrame([[1, 2, 3], [3, 5, 2], [4, 6, 2]])
print(df)
print()
a = pd.DataFrame([[1, 2, 3], [4, 5, 6], [7, 8, 9]], columns=[
                 'A', 'B', 'C'], index=['x', 'y', 'z'])
print(a)
print()
print(df.index)
print()
print(df.columns)
print()
print(df.describe())
print()
print(df.info())
print()
print(df.nunique())
print()
print(a['A'].unique())
print()
print(df.shape)
